# Generated by Django 5.0.6 on 2024-06-15 15:08

import auction_sales.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_number', models.CharField(default=auction_sales.utility.generate_item_number, max_length=3, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('item_status', models.CharField(choices=[('SO', 'SOLD'), ('NS', 'NOT SOLD')], default='NS', max_length=2)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
