# Generated by Django 5.0.6 on 2024-06-15 15:08

from django.db import migrations, models

import auction_sales


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('item_status', models.CharField(choices=[('SO', 'SOLD'), ('NS', 'NOT SOLD')], default='NS', max_length=2)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
